/**
 * Translation Generator Script
 * 
 * This script:
 * 1. Reads the existing TRANSLATIONS from translations.ts
 * 2. Collects all strings that need translation across the app
 * 3. Calls Claude API to generate translations for all 14 languages
 * 4. Outputs an updated translations object to be pasted into translations.ts
 * 
 * Usage: node scripts/gen-translations.js
 */

const fs = require('fs');
const path = require('path');

// Read existing translations file to get current keys
const translationsFile = fs.readFileSync(
  path.join(__dirname, '../src/lib/translations.ts'), 
  'utf8'
);

// Extract existing keys from ar block (first language = most complete)
const arMatch = translationsFile.match(/ar:\s*\{([^}]+(?:\{[^}]*\}[^}]*)*)\}/s);
const existingKeys = new Set();
if (arMatch) {
  const entries = arMatch[1].match(/"([^"]+)":/g);
  if (entries) entries.forEach(e => existingKeys.add(e.replace(/[":]/g, '')));
}

console.log(`Existing keys: ${existingKeys.size}`);
console.log('Sample existing keys:', [...existingKeys].slice(0, 10));

// New strings that need translating (collected from all pages)
const NEW_STRINGS = [
  // ─── Common UI ───
  "Save Changes",
  "Cancel",
  "Delete",
  "Edit",
  "Add",
  "Remove",
  "Enable",
  "Disable",
  "Loading...",
  "Error",
  "Success",
  "Warning",
  "Confirm",
  "Yes",
  "No",
  "Search",
  "Filter",
  "Export",
  "Import",
  "Close",
  "Back",
  "Next",
  "Previous",
  "Submit",
  "Reset",
  "Refresh",
  "View",
  "Copy",
  "Share",
  "Download",
  "Upload",
  "Select",
  "All",
  "None",
  "Apply",
  "Clear",
  "Done",
  "OK",
  "Update",
  "Create",
  "New",
  "Open",
  "More",
  "Less",
  "Show",
  "Hide",
  "Expand",
  "Collapse",
  "Details",
  "Summary",
  "Preview",
  "Print",
  "Help",
  "Info",
  "Note",
  "Required",
  "Optional",
  "Actions",
  "Options",
  "Settings",
  "Profile",
  "Name",
  "Email",
  "Password",
  "Description",
  "Status",
  "Date",
  "Time",
  "Location",
  "Type",
  "Category",
  "Tags",
  "Notes",
  "Comments",
  "Attachments",
  "Links",
  "Created",
  "Updated",
  "Deleted",
  "Active",
  "Inactive",
  "Pending",
  "Approved",
  "Rejected",
  "Draft",
  "Published",
  "Archived",
  "Unknown",
  "N/A",
  "No data found",
  "No results",
  "Loading data...",
  "Something went wrong",
  "Try again",
  "Copy link",
  "Copied!",

  // ─── Settings Page ───
  "Profile & Account",
  "General Settings",
  "Appearance",
  "Roles & Team",
  "Roles & Permissions",
  "Integrations & APIs",
  "Danger Zone",
  "Personal Information",
  "Full Name",
  "Display Name",
  "Phone Number",
  "Role",
  "Organization",
  "Member Since",
  "Last Login",
  "Account Security",
  "Two-Factor Authentication",
  "Change Password",
  "Current Password",
  "New Password",
  "Confirm Password",
  "Password updated successfully",
  "Passwords do not match",
  "Appearance Theme",
  "Theme",
  "Dark Mode",
  "Light Mode",
  "Auto (System)",
  "Accent Color",
  "Font Family",
  "Reset to Default",
  "Preview",
  "Save Appearance",
  "Platform Custom Order",
  "Arrange the platforms in the sidebar",
  "Invite Team Member",
  "Team Members",
  "Pending Invitations",
  "Send Invitation",
  "Email Address",
  "Select Role",
  "Invitation sent successfully",
  "Resend Invitation",
  "Revoke",
  "Admin",
  "Member",
  "Owner",
  "Viewer",
  "Custom Roles",
  "Create Role",
  "Edit Role",
  "Delete Role",
  "Role Name",
  "Permissions",
  "This is a system role and cannot be deleted",
  "No team members yet",
  "No pending invitations",
  "Invite your first team member",
  "Uplisting Integration",
  "WhatsApp Integration",
  "API Key",
  "Secret Key",
  "Access Token",
  "Webhook URL",
  "Test Connection",
  "Connected",
  "Not Connected",
  "Disconnect",
  "Reconnect",
  "Integration Settings",
  "Booking Sync",
  "Sync Now",
  "Last Synced",
  "Auto Sync",
  "Manual Sync",
  "Sync Frequency",
  "Every hour",
  "Every 6 hours",
  "Every 12 hours",
  "Every 24 hours",
  "Delete Account",
  "Delete Organization",
  "This action is irreversible",
  "Type your organization name to confirm",
  "Reset System to Defaults",
  "Danger Zone",
  "All data will be permanently deleted",

  // ─── Bookings ───
  "Bookings",
  "All Bookings",
  "New Booking",
  "Booking Details",
  "Booking ID",
  "Guest Name",
  "Check-in",
  "Check-out",
  "Nights",
  "Guests",
  "Adults",
  "Children",
  "Total Amount",
  "Paid",
  "Unpaid",
  "Partially Paid",
  "Refunded",
  "Cancelled",
  "Confirmed",
  "Pending",
  "Source",
  "Platform",
  "Property",
  "Room",
  "Unit",
  "Notes",
  "Special Requests",
  "Today",
  "Upcoming",
  "Past",
  "Search bookings...",
  "Filter by status",
  "Filter by platform",
  "Filter by property",
  "No bookings found",
  "Export bookings",
  "Booking confirmed",
  "Booking cancelled",
  "View details",
  "Edit booking",
  "Cancel booking",
  "Arrival",
  "Departure",
  "Duration",
  "Revenue",
  "Commission",
  "Net Revenue",
  "Cleaning Fee",
  "Service Fee",
  "Taxes",
  "Total",
  "Balance Due",
  "Payment Status",
  "Payment Method",
  "Card",
  "Bank Transfer",
  "Cash",
  "Guest Email",
  "Guest Phone",

  // ─── Properties ───
  "Properties",
  "All Properties",
  "Add Property",
  "Edit Property",
  "Property Name",
  "Property Type",
  "Address",
  "City",
  "Country",
  "Bedrooms",
  "Bathrooms",
  "Max Guests",
  "Base Price",
  "Amenities",
  "Photos",
  "Description",
  "Rules",
  "Check-in Time",
  "Check-out Time",
  "Minimum Stay",
  "Maximum Stay",
  "Availability",
  "Calendar",
  "Pricing",
  "Active Properties",
  "Inactive Properties",
  "Search properties...",
  "No properties found",
  "Property Details",
  "Floor Area",
  "Floor",
  "Building",
  "Unit Number",
  "DTCM Permit",
  "License Number",
  "Permit Expiry",
  "Property Manager",
  "Import Properties",
  "Sync Properties",

  // ─── Staff ───
  "Staff",
  "All Staff",
  "Add Staff Member",
  "Edit Staff Member",
  "Staff Member",
  "Staff Name",
  "Staff Role",
  "Cleaner",
  "Handyman",
  "Maintenance",
  "Supervisor",
  "Driver",
  "Availability",
  "Available",
  "Unavailable",
  "On Leave",
  "Assigned",
  "Unassigned",
  "Today's Tasks",
  "Scheduled Tasks",
  "Task History",
  "Performance",
  "No staff members",
  "Add your first staff member",
  "Staff Directory",
  "Contact",
  "Hire Date",
  "Department",
  "Hourly Rate",
  "Monthly Salary",
  "Skills",
  "Certifications",
  "Emergency Contact",
  "Working Hours",
  "Days Off",

  // ─── Scheduler ───
  "Scheduler",
  "Schedule",
  "Today's Schedule",
  "Weekly View",
  "Monthly View",
  "Add Task",
  "Edit Task",
  "Task Name",
  "Task Type",
  "Assign To",
  "Priority",
  "High",
  "Medium",
  "Low",
  "Due Date",
  "Start Time",
  "End Time",
  "Recurring",
  "One-time",
  "Daily",
  "Weekly",
  "Monthly",
  "Custom",
  "Completed",
  "In Progress",
  "Not Started",
  "Overdue",
  "Mark as Complete",
  "Reassign",
  "Add Note",
  "Task Notes",
  "Cleaning",
  "Inspection",
  "Maintenance",
  "Check-in Prep",
  "Check-out Inspection",
  "Deep Cleaning",
  "Quick Clean",
  "Visual Timeline",
  "Daily Run-Sheet",
  "Generated Schedule",
  "Train AI (Expert Feedback)",
  "Generate Schedule",
  "AI Schedule",
  "No tasks scheduled",
  "Add your first task",

  // ─── Accounting ───
  "Accounting",
  "Revenue",
  "Expenses",
  "Profit",
  "Loss",
  "Net Income",
  "Gross Revenue",
  "Operating Expenses",
  "VAT",
  "Tax",
  "Invoice",
  "Receipt",
  "Statement",
  "Report",
  "Financial Report",
  "Monthly Report",
  "Annual Report",
  "Chart of Accounts",
  "General Ledger",
  "Balance Sheet",
  "Income Statement",
  "Cash Flow",
  "Transactions",
  "Income",
  "Expense",
  "Transfer",
  "Refund",
  "Payment",
  "Deposit",
  "Withdrawal",
  "Currency",
  "AED",
  "USD",
  "EUR",
  "Amount",
  "Reference",
  "Category",
  "Account",
  "Period",
  "From",
  "To",
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
  "Q1",
  "Q2",
  "Q3",
  "Q4",
  "YTD",
  "MTD",

  // ─── Reservations ───
  "Reservations",
  "Upcoming Reservations",
  "Past Reservations",
  "Reservation Details",
  "Guest",
  "Room Type",
  "Reservation ID",
  "Confirmation Number",
  "Modify",
  "No reservations found",

  // ─── Channel Management ───
  "Channel Management",
  "Channels",
  "Airbnb",
  "Booking.com",
  "VRBO",
  "Expedia",
  "Direct Booking",
  "Channel Performance",
  "Listing",
  "Sync",
  "Rate Plan",
  "Availability Block",
  "Stop Sell",
  "Open",
  "Blocked",
  "Channel Settings",
  "Connect Channel",
  "Disconnect Channel",

  // ─── Host Management ───
  "Host Management",
  "Hosts",
  "Property Owner",
  "Owner Portal",
  "Revenue Share",
  "Management Fee",
  "Owner Statement",
  "Owner Report",
  "Monthly Statement",
  "Send Statement",
  "Owner Details",
  "Bank Details",
  "IBAN",
  "Bank Name",
  "Account Holder",
  "Commission Rate",

  // ─── Revenue Management ───
  "Revenue Management",
  "Dynamic Pricing",
  "Base Rate",
  "Minimum Rate",
  "Maximum Rate",
  "Seasonal Pricing",
  "Weekend Pricing",
  "Occupancy",
  "ADR",
  "RevPAR",
  "OTA Rate",
  "Direct Rate",
  "Discounts",
  "Promotions",
  "Last Minute",
  "Early Bird",
  "Long Stay",
  "Weekend",
  "Peak Season",
  "Low Season",

  // ─── Chat ───
  "Chat",
  "Messages",
  "New Message",
  "Send",
  "Reply",
  "Forward",
  "Archive",
  "Mark as Read",
  "Mark as Unread",
  "Guest Chat",
  "Team Chat",
  "Broadcast",
  "Template",
  "AI Reply",
  "Translate",
  "Attachment",
  "Emoji",
  "WhatsApp",
  "No messages",
  "Type a message...",
  "Sending...",
  "Delivered",
  "Read",
  "Failed",
  "Online",
  "Offline",
  "Last seen",

  // ─── General Status / Indicators ───
  "View All",
  "See More",
  "Show Less",
  "per night",
  "per month",
  "per year",
  "nights",
  "days",
  "hours",
  "minutes",
  "ago",
  "just now",
  "yesterday",
  "Last 7 days",
  "Last 30 days",
  "Last 90 days",
  "This month",
  "This year",
  "All time",
  "Date Range",
  "Start Date",
  "End Date",
  "Apply Filter",
  "Clear Filter",
  "Sort by",
  "Ascending",
  "Descending",
  "Newest First",
  "Oldest First",
  "A-Z",
  "Z-A",
  "Highest First",
  "Lowest First",
  "Page",
  "of",
  "items",
  "per page",
  "Go to page",
  "First",
  "Last",
];

// Filter out strings that already exist in TRANSLATIONS
const stringsToTranslate = NEW_STRINGS.filter(s => !existingKeys.has(s));
console.log(`\nStrings already in TRANSLATIONS: ${NEW_STRINGS.length - stringsToTranslate.length}`);
console.log(`New strings to translate: ${stringsToTranslate.length}`);

// Output the list for use in translation generation
fs.writeFileSync(
  path.join(__dirname, 'strings-to-translate.json'),
  JSON.stringify(stringsToTranslate, null, 2)
);

console.log('\nWritten to scripts/strings-to-translate.json');
console.log('Now run gen-translations-claude.js to generate the translations');
